### ISSUE TITLE
Some suggestions for the game

### ISSUE THREAD

**Issue by Clauvin** [AlexanderWild/ShadowsBehindTheThrone#1]
Hello! I played the game a bit and have some suggestions for it - also, thanks for working on it and taking the concept of That Which Sleeps forward :D

- 1 - Flesh Armies could have a power where you ask them to retreat, instead of endlessly attacking until they are dead? Just to make them less enough of a threat to allow players to stop an endless attack to their unguarded territories, using political manipulation to stop the war agains them?

- 2 - New Agent Suggestion: the Peerless Warrior. Basically a one-man army that, while not invincible, has 15 HP and can fight as an army, being also able to recover more than 1 HP through recruiting. Can be targeted by armies as they realize the threat he is. Won't target units with less then 4 Max HP as they are way below him in martial strength.

- 3 - About Enthralled Paladins: given their modus operandi, they should be able to attack people you choose them to, right? Having an Enthralled Paladin and not being able to attack other Paladins is kind of a bother :/ Of course, if they attack someone in a populated place without evidence or orders, this automatically raises the flag about them.

- 4 - Nevermind, I thought that Winter powers weren't available for the option where you have all the powers, but they were there, my mistake.

Thanks for reading :)

**Comment by AlexanderWild** [comment]
Hey, thanks for taking the time to comment. First issue makes sense, they should be able to do some kind of retreat, maybe move into a defensive position, which gives them more protection but prevents them from attacking? Should be simple enough, and doesn't make them too complex.

Regarding the last bit of question 1 (using politics to stop wars) and 2 and 3:
How agents behave in combat, and how they behave with regards to war, is currently being worked on.  The aim is to make enemy agents far more complex, and more tied into their societies. The nobles should be able to vote to assign their agents to particular 'specialities'. Paladins would hunt the enthralled agents, but during wars the agents could be turned into generals, to improve combat performance of armies, during plagues they could be equipped with medical teams and go try to quarantine/heal the infected. This would mean AI improvements, so they should be able to handle combat vs enthralled. Ideally you'd find it hard to kill them, but could do enough damage to make them retreat and leave your agents alone for a bit.
This means that war will be changed a bit, politics will be expanded so the nobles vote on current issues to select how to respond and how to deploy the agents, and agents AI will need to be upgraded. A lot to do.

All this depends on work which is currently underway. We really want the agents to be unique, and this involves a large graphics improvement, so they have unique faces the player can remember, even if they change their tasks.

Regarding point 2, it does seem like a good idea, and would allow you to interact with the new agents in an interesting way, but we need to avoid giving the player too much tactical flexibility, as it is probably very easy to trick the human military AI, and we don't really have the time to implement a complex planning algorithm for them, so we want to keep large military conflicts rather simple, in behaviour, to avoid giving the player the ability to win any confict by just tricking a bad AI.

Was going to answer about 4, but I note you've solved that already.

Anyway, thanks again for the points. Hopefully the upcoming changes will be to your liking.

**Comment by Clauvin** [comment]
You're welcome, and having received answers (thanks for answering my questions :) ), I'm closing this issue!
